services:
    traceabilitydriver:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - URL=https://127.0.0.1:5445
        # - EnableMSC=true 
        # - MongoDB__ConnectionString=mongodb://admin:password@mongodb_test:27017/TraceabilityDriverTests?authSource=admin
        - MongoDB__DatabaseName=TraceabilityDriverTests
        - SqlServer__ConnectionString=Server=sqlserver_test;Database=TraceabilityDriverTests;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
        - Authentication__Password=changeme
        - GDST__CapabilityTest__ApiKey=c8966620-9b28-4bb2-b071-5d86554dc9af
        - GDST__CapabilityTest__SolutionName=Traceability Driver
        - GDST__CapabilityTest__PGLN=urn:gdst:example.org:party:TraceabilityDriver.001
        - GDST__CapabilityTest__URL=https://127.0.0.1:7034
        # - Authentication__APIKey__HeaderName=X-API-KEY
        # - Authentication__APIKey__ValidKeys__0=test
        # - Authentication__APIKey__ValidKeys__1=test_2
        - TD_MAPPINGS_FOLDER
        ports:
            - "5444:8080"
            - "5445:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${TD_MAPPINGS_FOLDER}:/app/bin/Debug/net8.0/Mappings
        networks:
            - dev-network

    mongodb:
        image: mongo:latest
        container_name: mongodb_test
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        volumes:
            - mongodb_test_data:/data/db
        networks:
            - dev-network

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver_test
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
            - "1433:1433"
        volumes:
            - sqlserver_test_data:/var/opt/mssql
        networks:
            - dev-network

volumes:
  mongodb_test_data:
  sqlserver_test_data:

networks:
  dev-network:
    driver: bridge