// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraceabilityDriver.Services;

#nullable disable

namespace TraceabilityDriver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraceabilityDriver.Models.DB.Sql.EPCISEventSqlDocument", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("BizStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventKey")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EPCISEvents_EventId");

                    b.HasIndex("EventKey", "DeploymentVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_EPCISEvents_EventKey_DeploymentVersion")
                        .HasFilter("[EventKey] IS NOT NULL");

                    b.ToTable("EPCISEvents");
                });

            modelBuilder.Entity("TraceabilityDriver.Models.DB.Sql.EventSearchSqlDocument", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BizStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeploymentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventKey")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("EventTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocationGLN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartyPGLN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductGTIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_EventSearchDocuments_Action");

                    b.HasIndex("BizStep")
                        .HasDatabaseName("IX_EventSearchDocuments_BizStep");

                    b.HasIndex("DeploymentVersion")
                        .HasDatabaseName("IX_EventSearchDocuments_DeploymentVersion");

                    b.HasIndex("EPC")
                        .HasDatabaseName("IX_EventSearchDocuments_EPC");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventSearchDocuments_EventId");

                    b.HasIndex("EventKey")
                        .HasDatabaseName("IX_EventSearchDocuments_EventKey");

                    b.HasIndex("EventTime")
                        .HasDatabaseName("IX_EventSearchDocuments_EventTime");

                    b.HasIndex("LocationGLN")
                        .HasDatabaseName("IX_EventSearchDocuments_LocationGLN");

                    b.HasIndex("PartyPGLN")
                        .HasDatabaseName("IX_EventSearchDocuments_PartyPGLN");

                    b.HasIndex("ProductGTIN")
                        .HasDatabaseName("IX_EventSearchDocuments_ProductGTIN");

                    b.HasIndex("RecordTime")
                        .HasDatabaseName("IX_EventSearchDocuments_RecordTime");

                    b.ToTable("EventSearchDocuments");
                });

            modelBuilder.Entity("TraceabilityDriver.Models.DB.Sql.LogModelSql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("TraceabilityDriver.Models.DB.Sql.MasterDataSqlDocument", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("DeploymentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ElementJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ElementId", "DeploymentVersion")
                        .IsUnique()
                        .HasDatabaseName("IX_MasterDataDocuments_ElementId_DeploymentVersion")
                        .HasFilter("[DeploymentVersion] IS NOT NULL");

                    b.ToTable("MasterDataDocuments");
                });

            modelBuilder.Entity("TraceabilityDriver.Models.DB.SyncHistoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeploymentVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventsCreated")
                        .HasColumnType("int");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("int");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentVersion", "EndTime")
                        .HasDatabaseName("IX_SyncHistory_DeploymentVersion_EndTime");

                    b.ToTable("SyncHistory");
                });

            modelBuilder.Entity("TraceabilityDriver.Models.Traceback.TracebackItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Created")
                        .HasColumnType("bit");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TracebackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TracebackId")
                        .HasDatabaseName("IX_TracebackItems_TracebackId");

                    b.HasIndex("TracebackId", "ItemType", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_TracebackItems_Traceback_Type_Item");

                    b.ToTable("TracebackItems", (string)null);
                });

            modelBuilder.Entity("TraceabilityDriver.Models.Traceback.TracebackRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventsCreated")
                        .HasColumnType("int");

                    b.Property<int>("EventsUpdated")
                        .HasColumnType("int");

                    b.Property<int>("MasterDataCreated")
                        .HasColumnType("int");

                    b.Property<int>("MasterDataUpdated")
                        .HasColumnType("int");

                    b.Property<string>("RequestedEpcs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Tracebacks_StartTime");

                    b.ToTable("Tracebacks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
