services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_unit_test
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "37017:27017"
    volumes:
      - mongodb_unit_test_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_unit_test
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "3433:1433"
    volumes:
      - sqlserver_unit_test_data:/var/opt/mssql

volumes:
  mongodb_unit_test_data:
  sqlserver_unit_test_data: