using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TraceabilityEngine.Interfaces.DB.DocumentDB;
using TraceabilityEngine.Interfaces.Models.Identifiers;
using TraceabilityEngine.Util.Interfaces;

namespace TraceabilityEngine.Interfaces.Driver
{
    public interface ITEDriverTradingPartner : ITEDocumentObject
    {
        long ID { get; set; }
        long AccountID { get; set; }
        string Name { get; set; }
        IPGLN PGLN { get; set; }
        string DigitalLinkURL { get; set; }
        IDID DID { get; set; }

        /// <summary>
        /// This is an API Key that can be used by the account to request data from this trading partner. This API Key
        /// would be generated by the trading partner and sent to the account.
        /// </summary>
        string RequestingAPIKey { get; set; }

        /// <summary>
        /// This is an API Key that can be used by this trading partner to request data from the account. This API Key
        /// would be generated by the account and sent to the trading partner.
        /// </summary>
        string ReceivingAPIKey { get; set; }
        string ToJson();
        void FromJson(string json);
    }
}
