name: Build, Test and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore .v2.sln

    - name: Build
      run: dotnet build .v2.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test .v2.sln --configuration Release --no-build

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet publish TraceabilityDriver/TraceabilityDriver.csproj --configuration Release --output publish-output

    - name: Zip Release Files
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd publish-output
        zip -r ../TraceabilityDriver-${{ github.ref_name }}.zip .

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Traceability Driver ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          TraceabilityDriver-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 